language: python
python:
  - 3.6
branches:
  only:
    - master
    - develop
notifications:
  email: false



dist: trusty
sudo: required

# Install packages
install:
  - docker-compose build
  - docker-compose up 
  - docker-compose run app init 
  - docker-compose stop

# Run test
script:
  - ./runtest.sh

# Calculate coverage
#after_success:
#  - coveralls

cache:
  pip: true
  apt: true
  directories:
    - $HOME/miniconda
