language: python
python:
  - 3.6
branches:
  only:
    - master
    - develop
notifications:
  email: false



dist: trusty
sudo: required

# Install packages
install:
  - docker-compose build

# Run test
script:
  - docker-coverage run --service-ports --use-aliases --rm app test_cov

# Calculate coverage
after_success:
  - coveralls

cache:
  pip: true
  apt: true
  directories:
    - $HOME/miniconda
