version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    tty: true

  db:
    image: postgres

  celery:
    build: .
    command: "dockerize -wait tcp://rabbitmq:5672 -timeout 60s celery -A polyglot_server worker -l info"
    depends_on:
      - rabbitmq

  app:
    build: .
    command: ./start.sh
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - db
      - celery
    tty: true
    environment:
      - SOURCE_DATA_DIRECTORY = 'polyglot_source'
      - POLYGLOT_DATA_DIRECTORY = 'polyglot_data'
    #volumes:
    #  - polyglot_source:/polyglot-server-master/polyglot_source
    #  - polyglot_data:/polyglot-server-master/polyglot_data
    volumes:
      - ./polyglot_source:/polyglot-server-master/polyglot_source
      - ./polyglot_data:/polyglot-server-master/polyglot_data
      - ./pgdb:/polyglot-server-master/pgdb
      - ./polyglot_server:/polyglot-server-master/polyglot_server

volumes:
  polyglot_source:
    driver: "local"
  polyglot_data:
    driver: "local"
  pgdb:
    driver: "local"
  polyglot_server:
    driver: "local"