# Generated by Django 2.0 on 2018-03-09 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_choice', models.CharField(choices=[('C', 'Choice field'), ('S', 'String'), ('N', 'Numeric')], default='C', max_length=1)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AnnotationCategory',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_choice',
        ),
        migrations.AddField(
            model_name='annotationfield',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='annotator.Annotation'),
        ),
    ]
