# Generated by Django 2.0 on 2018-03-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0004_auto_20180205_1247'),
        ('annotator', '0003_auto_20180309_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='corpus',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, to='pgdb.Corpus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='item_type',
            field=models.CharField(choices=[('U', 'Utterance'), ('W', 'Word'), ('Y', 'Syllable'), ('P', 'Phone')], default='P', max_length=1),
        ),
    ]
