# Generated by Django 2.0 on 2018-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20180312_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationfield',
            name='annotation_choice',
            field=models.CharField(choices=[('C', 'Choice field'), ('S', 'String'), ('B', 'Boolean'), ('N', 'Numeric')], default='C', max_length=1),
        ),
    ]
