# Generated by Django 2.0 on 2018-01-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='source_directory',
            field=models.FilePathField(allow_files=False, allow_folders=True, default='', path='/mnt/e/Data/PolyglotData'),
        ),
        migrations.AlterField(
            model_name='database',
            name='influxdb_admin_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='influxdb_http_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='influxdb_meta_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='influxdb_udp_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='neo4j_admin_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='neo4j_bolt_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='neo4j_http_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='neo4j_https_port',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='consonant_freq_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='/mnt/e/bestiary-data', recursive=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='file_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='/mnt/e/Data/PolyglotData', recursive=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='low_freq_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='/mnt/e/bestiary-data', recursive=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='vowel_freq_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='/mnt/e/bestiary-data', recursive=True),
        ),
    ]
