# Generated by Django 2.0 on 2018-02-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgdb', '0002_auto_20180129_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=False)),
                ('can_listen', models.BooleanField(default=False)),
                ('can_view_detail', models.BooleanField(default=False)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdb.Corpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='corpus',
            name='users',
            field=models.ManyToManyField(through='pgdb.CorpusPermissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
