# Generated by Django 2.0 on 2018-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0004_auto_20180205_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuspermissions',
            name='can_annotate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpuspermissions',
            name='can_view_annotations',
            field=models.BooleanField(default=False),
        ),
    ]
