# Generated by Django 2.0 on 2018-04-02 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgdb', '0005_auto_20180315_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='export_file_name',
        ),
        migrations.AddField(
            model_name='query',
            name='annotation_type',
            field=models.CharField(choices=[('U', 'Utterance'), ('W', 'Word'), ('S', 'Syllable'), ('P', 'Phone')], default='U', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='corpus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pgdb.Corpus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='query',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
