# Generated by Django 2.0 on 2018-05-30 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0007_auto_20180417_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrichment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('running', models.BooleanField(default=False)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgdb.Corpus')),
            ],
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
