# Generated by Django 2.0.7 on 2018-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0011_auto_20180711_1632'),
        ('pgdb', '0011_auto_20180704_1746'),
    ]

    operations = [
    ]
