# Generated by Django 2.0.7 on 2018-07-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0012_merge_20180712_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name_plural': 'Queries'},
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='consonant_freq_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='polyglot_data', recursive=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='file_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='polyglot_source', recursive=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='low_freq_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='polyglot_data', recursive=True),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='vowel_freq_path',
            field=models.FilePathField(match='*.wav', max_length=250, path='polyglot_data', recursive=True),
        ),
    ]
