# Generated by Django 2.0 on 2018-08-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0013_auto_20180801_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acousticanalysis',
            name='script',
        ),
        migrations.RemoveField(
            model_name='discourse',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='soundfile',
            name='discourse',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='corpus',
        ),
        migrations.DeleteModel(
            name='AcousticAnalysis',
        ),
        migrations.DeleteModel(
            name='Discourse',
        ),
        migrations.DeleteModel(
            name='PraatScript',
        ),
        migrations.DeleteModel(
            name='SoundFile',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
