# Generated by Django 2.0.7 on 2018-08-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgdb', '0015_auto_20180717_1510'),
        ('pgdb', '0014_auto_20180801_0851'),
    ]

    operations = [
    ]
