# Generated by Django 2.0 on 2019-06-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iscan', '0003_auto_20190530_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpuspermissions',
            name='can_query',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corpuspermissions',
            name='is_whitelist_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='corpus',
            name='corpus_type',
            field=models.CharField(choices=[('T', 'Tutorial'), ('P', 'Public'), ('N', 'Private (non-restricted)'), ('R', 'Restricted')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('G', 'Guest'), ('A', 'Annotator'), ('R', 'Researcher'), ('U', 'Unlimited researcher')], default='G', max_length=1),
        ),
    ]
