# Generated by Django 2.2.2 on 2019-09-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iscan', '0004_auto_20190604_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTask',
            fields=[
                ('task_id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('running', models.BooleanField(default=True)),
                ('failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('corpus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iscan.Corpus')),
            ],
            options={
                'verbose_name_plural': 'Background Tasks',
            },
        ),
        migrations.CreateModel(
            name='SpadeScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpus_name', models.CharField(max_length=100)),
                ('script_name', models.CharField(max_length=100)),
                ('reset', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iscan.BackgroundTask')),
            ],
            options={
                'verbose_name_plural': 'Spade Scripts',
            },
        ),
    ]
